### ISSUE TITLE
Cannot build with PDFTron

### ISSUE THREAD

**Issue by bbozhidarov** [PDFTron/pdftron-flutter#21]
When I try to build a Flutter project using PDFTron, the build fails. Just yesterday I was able to do so, but after updating some packages now it fails. I tried `flutter pub cache repair`, also tried to delete .pub-cache folder, cleaned project, running `flutter pub get` again, but no success. This is the output of the console when trying to build.

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
Error detected in pubspec.yaml:
No file or variants found for asset: packages/timezone/data/2019c.tzf.

Note: C:\Users\HP\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\connectivity-0.4.9\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

C:\Users\HP\AppData\Local\Pub\Cache\git\pdftron-flutter-e0d6f41ceb2a9be692a3693a6a7ad275c9cfcc4d\android\src\main\java\com\pdftron\pdftronflutter\FlutterDocumentActivity.java:103: error: onOpenDocError() in FlutterDocumentActivity cannot implement onOpenDocError() in TabHostListener
    public void onOpenDocError() {
                ^
  return type void is not compatible with boolean
C:\Users\HP\AppData\Local\Pub\Cache\git\pdftron-flutter-e0d6f41ceb2a9be692a3693a6a7ad275c9cfcc4d\android\src\main\java\com\pdftron\pdftronflutter\FlutterDocumentActivity.java:102: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pdftron_flutter:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Exception: Gradle task assembleDebug failed with exit code 1
```

This is the output of *flutter doctor --verbose*

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.900], locale bg-BG)
    • Flutter version 1.17.5 at C:\flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\HP\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 30.0.1
    • ANDROID_SDK_ROOT = C:\Users\HP\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!
```

And that's my `pubspec.yaml`:

```
name: App
description: MobileApp

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^7.0.9
  cached_network_image: ^2.0.0
  collection: ^1.14.11
  connectivity: ^0.4.8+2
  cupertino_icons: ^0.1.3
  date_util: ^0.1.4
  event_bus: ^1.1.1
  file_picker: ^1.6.0
  flutter_dotenv: ^2.1.0
  flutter_html: ^1.0.0
  flutter_js: ^0.0.2+1
  flutter_svg: ^0.17.4
  font_awesome_flutter: ^8.8.1
  geolocator: ^5.3.1
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11+1
  google_fonts: ^0.3.10
  http: ^0.12.0+4
  image_picker: ^0.6.4
  intl: ^0.16.0
  logging: ^0.11.4
  path_provider: ^1.6.5
  pdftron_flutter:
    git:
      url: git://github.com/PDFTron/pdftron-flutter.git
  permission_handler: ^4.4.0
  photo_view: ^0.9.2
  shared_preferences: ^0.5.6+3
  syncfusion_flutter_calendar: ^17.4.51-beta
  url_launcher: ^5.4.2
  webview_flutter: ^0.3.19+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^1.8.0
  built_value_generator: ^7.0.9
  mockito: ^4.1.1
  test: ^1.9.4

flutter:
  assets:
    - .env
    - .revision
  uses-material-design: true
```

Any help wold be appreciated. Thanks!
